name: Linux distros tests

on:
    pull_request:
        types: [labeled, synchronize]
    workflow_dispatch:
        inputs:
            test_type:
                type: choice
                description: Which series of tests to launch
                required: true
                options:
                - short
                - long
                - full

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    tests_short:
        name: Short (deb13 only, w/o cc)
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' || inputs.test_type == 'short' }}
        timeout-minutes: 45
        steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
        - name: run tests inside a debian13 docker
          run: tests/functional/docker/docker_build_and_run_tests.sh debian13 --no-pause-on-fail --slowness-factor=2
          env:
            DOCKER_TTY: false

    tests_long:
        name: Long (multi-distros, w/o cc)
        strategy:
            matrix:
                platform: [rockylinux10, debian13, 'opensuse16@opensuse/leap:16.0', ubuntu2604]
        runs-on: ubuntu-latest
        if: ${{ contains(github.event.pull_request.labels.*.name, 'tests:long') || inputs.test_type == 'long' }}
        timeout-minutes: 45
        steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
        - name: run tests inside a ${{ matrix.platform }} docker
          run: tests/functional/docker/docker_build_and_run_tests.sh ${{ matrix.platform }} --no-pause-on-fail --slowness-factor=2
          env:
            DOCKER_TTY: false

    tests_full:
        name: Full (exhaustive, w/ cc)
        strategy:
            matrix:
                platform: [rockylinux8, rockylinux9, rockylinux10, debian11, debian12, debian13, 'opensuse16@opensuse/leap:16.0', ubuntu2204, ubuntu2404, ubuntu2604]
        runs-on: ubuntu-latest
        if: ${{ contains(github.event.pull_request.labels.*.name, 'tests:full') || inputs.test_type == 'full' }}
        timeout-minutes: 45
        steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
        - name: run tests inside a ${{ matrix.platform }} docker
          run: tests/functional/docker/docker_build_and_run_tests.sh ${{ matrix.platform }} --consistency-check --no-pause-on-fail --slowness-factor=2
          env:
            DOCKER_TTY: false
